plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.8-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.49-beta' apply false

    // see https://plugins.gradle.org/plugin/com.matyrobbrt.mc.registrationutils for new versions
    id 'com.matyrobbrt.mc.registrationutils' version "1.21.0-0.2.2"
}

// refer to https://github.com/Matyrobbrt/RegistrationUtils for documentation
// this implementation differs slightly from the given example; project names
// are case-sensitive (i.e. we do not have "Fabric" as a project, we have "fabric")
registrationUtils {
    
    group 'io.github.jason13official.my_cool_mod.registration'

    projects {
        fabric { type 'fabric' }
        neoforge { type 'neoforge' }
        common { type 'common' }
    }
}